apiVersion: v1
kind: ConfigMap
metadata:
    name: config
data:
    config.yaml: |-
        storage_path: /db/db.sql
        http_server:
            address: :{{ .Values.service.targetPort }}
            read_header_timeout: 4s
            idle_timeout: 60s
        graceful_shutdown_timeout: 30s
        log_level: 0 # 0: info, -4: debuf