name: "Release"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: 'latest'
#   push:
#     branches:
#       - main


jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        id: release_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          VERBOSE: true
          WITH_V: false
          CUSTOM_TAG: ${{ github.event.inputs.tag }}

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.2"


      - name: Install Helm
        uses: azure/setup-helm@v4


      - name: Login to DockerHub
        if: ${{ success() }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            len4i/pizza-store:${{steps.release_tag.outputs.new_tag}}
            len4i/pizza-store:latest

      - name: Pack Helm chart and push
        shell: bash
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
            yq -i '.version = "${{steps.release_tag.outputs.new_tag}}"' helm-chart/Chart.yaml
            yq -i '.controllerManager.manager.image.tag = "${{steps.release_tag.outputs.new_tag}}"' helm-chart/values.yaml
            helm package ./helm-chart -u 
            helm registry login registry-1.docker.io -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            helm push pizza-store-helm-${{steps.release_tag.outputs.new_tag}}.tgz oci://registry-1.docker.io/len4i

      - name: Create Release
        if: ${{ success() }}
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: pizza-store-helm-${{steps.release_tag.outputs.new_tag}}.tgz
          tag: ${{steps.release_tag.outputs.new_tag}}
          generateReleaseNotes: true

